# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: danf.us
email: null # partnershipgarden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Dan Farrell isn't that interesting.  Visit some other site. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danf.us" # the base hostname & protocol for your site
twitter_username: null
github_username:  farrellit

# Build settings
markdown: kramdown
